print("Здравствуйте, вы проходите анкету")
first_name = input("Имя:")
last_name = input("Фамилия:")
age = input("Год рождения:")
horoscope = input("Кто вы по городскопу:")
question = input("что вы ожидаете от курса?")
print("Спасибо за ваши ответы")
print("ФИО:", first_name, last_name)
print("Год рождения:", age)
print("Кто вы по городскопу:", horoscope)
print("что вы ожидаете от курса?", question)
